/*
	API_TIMESHEETAPI_TIMESHEETExample.h
	Provides example and test runs the service's proxy methods.
	Generated by SudzC.com
*/
@interface API_TIMESHEETAPI_TIMESHEETExample : NSObject {
}
-(void)run;
@end
		